sudo: false
dist: trusty
language: clojure
lein: 2.7.1
before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
script:
  - ./scripts/test.sh $TEST
  - ./scripts/submit-to-coveralls.sh $TEST
env:
  matrix:
  - TEST=clj
  - TEST=cljs
jdk:
  - oraclejdk8
node_js:
  - lts/*
cache:
  directories:
  - "$HOME/.m2"
